######################################################################
# Automatically generated by qmake (2.01a) ?? 14. ??? 20:18:23 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . debug release
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
RESOURCES += application.qrc
