######################################################################
# Automatically generated by qmake (2.01a) ?? 15. ??? 16:56:42 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . debug release
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
RESOURCES += application.qrc
